name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # deliver feedback for all matrix combinations
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [gcc, clang, msvc]
        sanitize: ["", address]

        include:
          - compiler: msvc
            cmake_conf_preset: conan-default    # TODO: https://github.com/conan-io/conan/issues/18059
            c_compiler: cl
            cxx_compiler: cl

          - compiler: gcc
            cmake_conf_preset: conan-release
            c_compiler: gcc
            cxx_compiler: g++

          - compiler: clang
            cmake_conf_preset: conan-release
            c_compiler: clang
            cxx_compiler: clang++

        exclude:
          - os: windows-latest
            compiler: gcc

          - os: windows-latest
            compiler: clang

          - os: ubuntu-latest
            compiler: msvc

          - os: macos-latest
            compiler: msvc

          - os: macos-latest
            compiler: gcc


    env:
      CC: ${{matrix.c_compiler}}
      CXX: ${{matrix.cxx_compiler}}


    steps:
    - name: Install libc++
      if: matrix.compiler == 'clang'
      run: |
        sudo apt-get update
        sudo apt-get install -y libc++-dev libc++abi-dev

    - uses: actions/checkout@v4

    - name: Setup conan package manager
      uses: conan-io/setup-conan@v1
        
    - name: Conan install - download and/or build libraries
      run: conan install . --build=missing -pr:a .github/workflows/conan_base -pr:a .github/workflows/conan_${{matrix.compiler}}

    - name: CMake configure - generate build system files
      run: cmake --preset=${{matrix.cmake_conf_preset}} -DTBBSS_SANITIZE=${{matrix.sanitize}}

    - name: CMake build - build C/C++ code
      run: cmake --build --preset=conan-release

    - name: Tests run (Windows)
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        call build\generators\conanrun.bat
        build\Release\tbbss_tests.exe

    - name: Tests run (Posix)
      if: matrix.os != 'windows-latest'
      run: |
        source build/Release/generators/conanrun.sh
        ./build/Release/tbbss_tests -d
