name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # deliver feedback for all matrix combinations
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            conan_os: Windows
          - os: ubuntu-latest
            conan_os: Linux
          - compiler: gcc
            conan_compiler: gcc
          - compiler: clang
            conan_compiler: clang
          - compiler: cl
            conan_compiler: Visual Studio
        exclude:
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang
          - os: ubuntu-latest
            compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Setup conan package manager
      uses: conan-io/setup-conan@v1
        
    - name: Conan install - download and/or build libraries
      run: conan install . -s os=${{matrix.conan_os}} -s compiler=${{matrix.conan_compiler}} --build=missing

    - name: CMake configure - generate build system files
      run: cmake --preset=conan-release

    - name: CMake build - build C/C++ code
      run: cmake --build --preset=conan-release

    - name: Tests run
      working-directory: build/Release
      run: tbbss_tests
